name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Deploy to EC2
      run: |
        ssh -T ubuntu@${{ secrets.IP }} << 'EOF'
          cd /home/ubuntu/neobackend
          git pull origin main  # Fa un 'pull' dell'ultima versione del codice
            npm install  # Rinstalla le dipendenze (se necessario)
            pm2 restart all  # Riavvia tutte le istanze gestite da PM2
            pm2 save  # Salva la configurazione per il riavvio del server
        EOF
