name: Build e Deploy Manuale

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch da buildare e deployare'
        required: true
        default: 'main'
      ambiente:
        description: 'Ambiente (es: test, prod)'
        required: true
        default: 'test'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del branch selezionato
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Installa dipendenze
        run: npm install

      - name: Build del progetto
        run: npm run build

      - name: Deploy al server remoto
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/"  # o la tua cartella di build
          target: "/var/www/${{ github.event.inputs.ambiente }}"
